# Generated by Django 5.0.4 on 2024-04-10 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=300)),
                ('date_start', models.DateField()),
                ('date_finish', models.DateField()),
                ('place', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Merch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=300)),
                ('image', models.ImageField(upload_to='static/images/merch')),
            ],
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('image', models.ImageField(upload_to='static/images/partners')),
                ('link', models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('gender', models.CharField(choices=[('G', 'G'), ('B', 'B')], default='B', max_length=1)),
                ('age', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=2000)),
                ('answer', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='ImageExposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='static/images/expositions')),
                ('exposition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.exposition')),
            ],
        ),
        migrations.CreateModel(
            name='ImageExpositionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exposition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.exposition')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.imageexposition')),
            ],
        ),
        migrations.CreateModel(
            name='ExpositionPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exposition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.exposition')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.partner')),
            ],
        ),
        migrations.AddField(
            model_name='exposition',
            name='partners',
            field=models.ManyToManyField(related_name='exposition_partner', through='app.ExpositionPartner', to='app.partner'),
        ),
        migrations.CreateModel(
            name='ImagePet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='static/images/pets')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.pet')),
            ],
        ),
        migrations.CreateModel(
            name='ExpositionPet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exposition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.exposition')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.pet')),
            ],
        ),
        migrations.AddField(
            model_name='exposition',
            name='pets',
            field=models.ManyToManyField(related_name='exposition_pet', through='app.ExpositionPet', to='app.pet'),
        ),
    ]
