# Generated by Django 5.0.4 on 2024-04-12 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_email', models.CharField(blank=True, max_length=500)),
                ('contact_email', models.CharField(blank=True, max_length=500)),
                ('contact_phone', models.CharField(blank=True, max_length=500)),
                ('contact_address', models.CharField(blank=True, max_length=500)),
                ('contact_telegram', models.CharField(blank=True, max_length=500)),
                ('contact_vkontakte', models.CharField(blank=True, max_length=500)),
                ('contact_odnoklassniki', models.CharField(blank=True, max_length=500)),
                ('statistic_pets', models.IntegerField(default=0)),
                ('statistic_volunteers', models.IntegerField(default=0)),
                ('statistic_pets_home', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='exposition',
            name='meta_description',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='exposition',
            name='meta_title',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='exposition',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('disabled', 'disabled')], default='active', max_length=10),
        ),
        migrations.AddField(
            model_name='exposition',
            name='top_image',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='pet',
            name='type',
            field=models.CharField(choices=[('cat', 'cat'), ('dog', 'dog')], default='cat', max_length=10),
        ),
        migrations.AlterField(
            model_name='exposition',
            name='alias',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='exposition',
            name='place',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='pet',
            name='gender',
            field=models.CharField(choices=[('girl', 'girl'), ('boy', 'boy')], default='boy', max_length=10),
        ),
    ]
