# Generated by Django 5.0.4 on 2024-04-15 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_basesettings_exposition_meta_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='basesettings',
            name='contract_file',
            field=models.FileField(blank=True, upload_to='static/files'),
        ),
        migrations.AddField(
            model_name='basesettings',
            name='full_description',
            field=models.CharField(blank=True, max_length=3000),
        ),
        migrations.AddField(
            model_name='basesettings',
            name='how_get_text',
            field=models.CharField(blank=True, max_length=3000),
        ),
        migrations.AlterField(
            model_name='imagepet',
            name='pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='app.pet'),
        ),
    ]
