# Generated by Django 5.0.4 on 2024-04-15 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_basesettings_contract_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exposition',
            name='alias',
        ),
        migrations.RemoveField(
            model_name='exposition',
            name='meta_description',
        ),
        migrations.RemoveField(
            model_name='exposition',
            name='meta_title',
        ),
        migrations.AddField(
            model_name='basesettings',
            name='meta_description',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='basesettings',
            name='meta_keywords',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='basesettings',
            name='meta_title',
            field=models.CharField(default='', max_length=300),
        ),
    ]
