# Generated by Django 5.0.4 on 2024-04-16 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_exposition_alias_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Merch',
        ),
        migrations.AddField(
            model_name='exposition',
            name='description',
            field=models.CharField(blank=True, max_length=3000),
        ),
        migrations.AlterField(
            model_name='exposition',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('past', 'past')], default='active', max_length=10),
        ),
    ]
