# Generated by Django 5.0.4 on 2024-04-19 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_callform_feedbackform_pickuppetform'),
    ]

    operations = [
        migrations.AddField(
            model_name='callform',
            name='status',
            field=models.CharField(choices=[('new', 'new'), ('done', 'done')], default='new', max_length=10),
        ),
        migrations.AddField(
            model_name='feedbackform',
            name='status',
            field=models.CharField(choices=[('new', 'new'), ('done', 'done')], default='new', max_length=10),
        ),
        migrations.AddField(
            model_name='pickuppetform',
            name='status',
            field=models.CharField(choices=[('new', 'new'), ('done', 'done')], default='new', max_length=10),
        ),
    ]
