# Generated by Django 5.0.4 on 2024-04-23 06:17

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_callform_status_feedbackform_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagepet',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=-1, scale=None, size=[800, None], upload_to='static/images/pets'),
        ),
    ]
